apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-adlists
  namespace: pihole-system
data:
  adlists.list: |

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-regex
  namespace: pihole-system
data:
  regex.list: |

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-env
  namespace: pihole-system
data:
  TZ: UTC
  DNS1: 127.0.0.1#5054
  DNS2: 127.0.0.1#5054
